/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChatApplication */

#ifndef _Included_ChatApplication
#define _Included_ChatApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChatApplication
 * Method:    startServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ChatApplication_startServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     ChatApplication
 * Method:    connectToServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ChatApplication_connectToServer
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
