/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChatClient */

#ifndef _Included_ChatClient
#define _Included_ChatClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChatClient
 * Method:    connectToServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ChatClient_connectToServer
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
